package com.rorono.a22recycler.utils

object FullNameCurrency {
    val fullNameCurrency = mapOf(
        "AUD" to "Australian dollar",
        "AZN" to "Azerbaijani manat",
        "GBP" to "British pound sterling",
        "AMD" to "Armenian dram",
        "BYN" to "Belarusian ruble",
        "BGN" to "Bulgarian lew",
        "BRL" to "Brazilian real",
        "HUF" to "Hungarian forints",
        "HKD" to "Hong Kong dollars",
        "DKK" to "Danish kroner",
        "USD" to "US dollar",
        "EUR" to "Euro",
        "INR" to "India rupee",
        "KZT" to "Kazakhstan tenge",
        "CAD" to "Canadian dollar",
        "KGS" to "Kyrgyzstan som",
        "CNY" to "Chinese yuan",
        "MDL" to "Moldova lei",
        "NOK" to "Norway crowns",
        "PLN" to "Polish zloty",
        "RON" to "Romanian leu",
        "XDR" to "Special Drawing Rights",
        "SGD" to "Singapore dollar",
        "TJS" to "Tajik somoni",
        "TRY" to "Turkish Lira",
        "TMT" to "New Turkmen manat",
        "UZS" to "Uzbekistan soums",
        "UAH" to "Ukrainian hryvnia",
        "CZK" to "Czech crowns",
        "SEK" to "Swedish kroner",
        "CHF" to "Swiss franc",
        "ZAR" to "South African rand",
        "KRW" to "Won Republic of Korea",
        "JPY" to "Japanese yen")
}